# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('contact1', models.DecimalField(decimal_places=0, max_digits=15)),
                ('contact2', models.DecimalField(decimal_places=0, max_digits=15)),
                ('contact3', models.DecimalField(decimal_places=0, max_digits=15)),
                ('permanent_address', models.CharField(max_length=100)),
                ('residential_address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
