# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0004_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='doc'),
        ),
    ]
