# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0005_auto_20160317_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
