# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0006_resume_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='first_name',
        ),
    ]
