# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpo', '0007_remove_resume_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='doc'),
        ),
    ]
